import { useEffect, useRef, useState } from "react";
import { Check, LoaderCircle, Mic, Sparkles, Square, X } from "lucide-react";
import "./smart-input.css";

export function SmartTextArea({api,value,onChange,setNotice,label,textareaProps={}}) {
  const [listening,setListening]=useState(false);const [busy,setBusy]=useState(false);const [preview,setPreview]=useState("");const recognitionRef=useRef(null);const baseRef=useRef("");
  useEffect(()=>()=>recognitionRef.current?.stop(),[]);
  const dictate=()=>{if(recognitionRef.current){recognitionRef.current.stop();return;}const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return setNotice?.("הכתבה קולית אינה נתמכת בדפדפן זה");const recognition=new Recognition();baseRef.current=String(value||'').trim();recognition.lang='he-IL';recognition.continuous=true;recognition.interimResults=true;recognition.onresult=(event)=>{const text=Array.from(event.results).map((result)=>result[0]?.transcript||'').join(' ').trim();onChange([baseRef.current,text].filter(Boolean).join('\n'));};recognition.onend=()=>{recognitionRef.current=null;setListening(false)};recognition.onerror=()=>setNotice?.('ההכתבה הופסקה. בדקו הרשאת מיקרופון.');recognitionRef.current=recognition;recognition.start();setListening(true);};
  const improve=async(action)=>{if(!String(value||'').trim())return;setBusy(true);try{const result=await api('/ai/text-polish',{method:'POST',body:JSON.stringify({text:value,action})});setPreview(result.text);}catch(error){setNotice?.(error.message)}finally{setBusy(false)}};
  return <div className="smart-text-field"><header><strong>{label}</strong><div><button type="button" className={listening?'listening':''} onClick={dictate}>{listening?<Square size={14}/>:<Mic size={15}/>}<span>{listening?'מאזין…':'הכתבה'}</span></button><details><summary>{busy?<LoaderCircle className="spin" size={15}/>:<Sparkles size={15}/>}<span>AI</span></summary><menu><button type="button" onClick={()=>improve('professional')}>ניסוח מקצועי</button><button type="button" onClick={()=>improve('structure')}>סידור וסעיפים</button><button type="button" onClick={()=>improve('shorten')}>קיצור</button><button type="button" onClick={()=>improve('language')}>שיפור שפה</button></menu></details></div></header><textarea {...textareaProps} value={value} onChange={(event)=>onChange(event.target.value)}/>{listening&&<div className="smart-listening"><i/><i/><i/><i/>מאזין ומוסיף לטקסט הקיים…</div>}{preview&&<section className="smart-preview"><strong>תצוגה מקדימה — הטקסט הקיים טרם הוחלף</strong><div>{preview}</div><footer><button type="button" onClick={()=>setPreview('')}><X size={14}/>ביטול</button><button type="button" onClick={()=>{onChange(preview);setPreview('')}}><Check size={14}/>החלפה</button></footer></section>}</div>;
}
