ALTER TABLE projects ADD COLUMN IF NOT EXISTS floor TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS apartment_number TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS entrance_code TEXT NOT NULL DEFAULT '';
