map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen 8099 default_server;
    server_name _;

    allow 172.30.32.2;
    deny all;

    root /var/www/projects;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /health {
        access_log off;
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}

server {
    listen 8686;
    server_name _;

    root /var/www/projects;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /health {
        access_log off;
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
