import { useEffect, useRef, useState } from "react";
import { Mail, Sparkles, Trash2 } from "lucide-react";
import { AppModal } from "../../AppModal";
import { localDateTimeValue } from "../../dateTime";
import { SmartTextArea } from "../smart-input/SmartTextArea";
import "./meeting-summary.css";

const meetingDateValue=(value)=>value?new Date(value).toLocaleString('sv-SE',{timeZone:'Asia/Jerusalem'}).replace(' ','T').slice(0,16):localDateTimeValue();

export function MeetingSummaryForm({ api,onClose,onSubmit,setNotice,project,professionals=[],initial=null }) {
  const formRef=useRef(null);
  const [summary,setSummary]=useState(initial?.summary||"");
  const [followUp,setFollowUp]=useState(initial?.follow_up||"");
  const [tasks,setTasks]=useState([]);const [email,setEmail]=useState({subject:"",body:""});
  const [recipients,setRecipients]=useState([]);const [to,setTo]=useState([]);const [cc,setCc]=useState([]);const [busy,setBusy]=useState(false);
  useEffect(()=>{if(project?.id)api(`/projects/${project.id}/email-recipients`).then((result)=>setRecipients(result.recipients||[])).catch(()=>{})},[project?.id]);
  const analyze=async()=>{const liveSummary=String(formRef.current?.elements?.namedItem('summary')?.value??summary).trim();const liveFollowUp=String(formRef.current?.elements?.namedItem('followUp')?.value??followUp).trim();if(!liveSummary)return setNotice('יש להזין סיכום לפני חילוץ פעולות');setSummary(liveSummary);setFollowUp(liveFollowUp);setBusy(true);try{const result=await api('/ai/meeting-actions',{method:'POST',body:JSON.stringify({text:`${liveSummary}\n${liveFollowUp}`})});setTasks((result.tasks||[]).map((task)=>({...task,enabled:true,assigneeProfessionalId:professionals.find((person)=>String(person.displayName||person.display_name||'').includes(task.assigneeName))?.id||''})));setEmail(result.email||{subject:'סיכום פגישה והמשך טיפול',body:liveSummary});if(!(result.tasks||[]).length)setNotice('הניתוח הושלם, אך לא זוהו פעולות המשך מפורשות')}catch(error){const fallback=liveFollowUp.split(/\n|[.;•]/).map((line)=>line.trim()).filter((line)=>line.length>4).slice(0,8).map((line)=>({title:line.slice(0,120),description:line,priority:'normal',dueDate:'',assigneeProfessionalId:'',enabled:true}));setTasks(fallback);setEmail({subject:`סיכום פגישה – ${project?.name||''}`.trim(),body:`שלום,\n\nלהלן סיכום הפגישה:\n${liveSummary}\n\nהמשך טיפול:\n${liveFollowUp}\n\nבברכה`});setNotice(`הופעלה חלופה מקומית: ${error.message}`)}finally{setBusy(false)}};
  const openMail=async()=>{const toEmails=recipients.filter((item)=>to.includes(String(item.id))).map((item)=>item.email);const ccEmails=recipients.filter((item)=>cc.includes(String(item.id))).map((item)=>item.email);if(!toEmails.length)return setNotice('יש לבחור לפחות נמען אחד');await api(`/projects/${project.id}/email-draft-opened`,{method:'POST',body:JSON.stringify({meetingId:initial?.id,recipientCount:toEmails.length,ccCount:ccEmails.length})});window.location.href=`mailto:${toEmails.join(',')}?cc=${encodeURIComponent(ccEmails.join(','))}&subject=${encodeURIComponent(email.subject)}&body=${encodeURIComponent(email.body)}`;};
  const submit=(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);form.set('summary',summary);form.set('followUp',followUp);form.set('aiTasks',JSON.stringify(tasks.filter((task)=>task.enabled)));onSubmit(event,form);};
  const updateTask=(index,patch)=>setTasks((current)=>current.map((task,i)=>i===index?{...task,...patch}:task));
  return <AppModal title={initial?'עריכת סיכום פגישה':'סיכום פגישה חדש'} subtitle="הכתבה, ניסוח מקצועי, פעולות המשך וטיוטת מייל" onClose={onClose} className="meeting-summary-modal">
    <form ref={formRef} className="work-form meeting-summary-form" onSubmit={submit}>
      <label>תאריך ושעה<input type="datetime-local" name="meetingAt" required defaultValue={meetingDateValue(initial?.meeting_at)}/></label>
      <label>נוכחים<input name="attendees" defaultValue={initial?.attendees||''} placeholder="שמות מופרדים בפסיק"/></label>
      <label>שעות תכנון / ישיבה<input type="number" name="hours" min="0" max="24" step="0.5" placeholder="0" defaultValue={initial?.work_hours||''}/></label>
      <div className="wide"><SmartTextArea api={api} value={summary} onChange={setSummary} setNotice={setNotice} label="סיכום והחלטות" textareaProps={{name:'summary',required:true,rows:9,placeholder:'החלטות, תובנות ונושאים שעלו…'}}/></div>
      <div className="wide"><SmartTextArea api={api} value={followUp} onChange={setFollowUp} setNotice={setNotice} label="המשך טיפול" textareaProps={{name:'followUp',rows:4}}/></div>
      <div className="wide meeting-ai-actions"><button type="button" onClick={analyze} disabled={busy}><Sparkles size={16}/>{busy?'מנתח…':'הצע משימות וטיוטת מייל'}</button></div>
      {tasks.length>0&&<section className="wide meeting-task-suggestions"><header><h3>משימות מוצעות</h3><span>ערכו, השלימו תאריך ובחרו אילו משימות ליצור</span></header>{tasks.map((task,index)=><article key={index}><input type="checkbox" checked={task.enabled} onChange={(event)=>updateTask(index,{enabled:event.target.checked})}/><input value={task.title} onChange={(event)=>updateTask(index,{title:event.target.value})} placeholder="כותרת"/><input type="date" value={task.dueDate||''} onChange={(event)=>updateTask(index,{dueDate:event.target.value})} required={task.enabled}/><select value={task.assigneeProfessionalId||''} onChange={(event)=>updateTask(index,{assigneeProfessionalId:event.target.value})}><option value="">ללא אחראי</option>{professionals.map((person)=><option key={person.id} value={person.id}>{person.displayName||person.display_name}</option>)}</select><select value={task.priority} onChange={(event)=>updateTask(index,{priority:event.target.value})}><option value="normal">רגילה</option><option value="high">גבוהה</option><option value="urgent">דחופה</option></select><button type="button" onClick={()=>setTasks((current)=>current.filter((_,i)=>i!==index))}><Trash2 size={15}/></button><textarea value={task.description} onChange={(event)=>updateTask(index,{description:event.target.value})} placeholder="תיאור המשימה"/></article>)}</section>}
      {email.subject&&<section className="wide meeting-email-draft"><header><h3>טיוטת מייל</h3><button type="button" onClick={openMail}><Mail size={16}/>פתח במייל</button></header><label>נושא<input value={email.subject} onChange={(event)=>setEmail({...email,subject:event.target.value})}/></label><textarea value={email.body} onChange={(event)=>setEmail({...email,body:event.target.value})}/><div className="meeting-recipient-grid"><fieldset><legend>נמענים</legend>{recipients.map((item)=><label key={item.id}><input type="checkbox" checked={to.includes(String(item.id))} onChange={(event)=>setTo((current)=>event.target.checked?[...current,String(item.id)]:current.filter((id)=>id!==String(item.id)))}/>{item.name} · {item.email}</label>)}</fieldset><fieldset><legend>עותק (CC)</legend>{recipients.map((item)=><label key={item.id}><input type="checkbox" checked={cc.includes(String(item.id))} onChange={(event)=>setCc((current)=>event.target.checked?[...current,String(item.id)]:current.filter((id)=>id!==String(item.id)))}/>{item.name}</label>)}</fieldset></div></section>}
      <label className="wide meeting-attachments">תמונות ומסמכי הפגישה<input type="file" name="attachments" accept="image/*,application/pdf,.doc,.docx,.xlsx" multiple/></label>
      <div className="wide form-actions"><button type="button" className="ops-secondary" onClick={onClose}>ביטול</button><button className="ops-primary">{initial?'שמירת שינויים':'שמירת סיכום'}{tasks.some((task)=>task.enabled)?' ויצירת משימות':''}</button></div>
    </form>
  </AppModal>;
}
