import {useState} from 'react';
import {AppModal} from '../../AppModal';
import {DateInput} from '../../DateInput';
import './table-import.css';
import {groupEquipment} from './equipmentGrouping';

const labels={new:'חדשים',changed:'שינויים',unchanged:'ללא שינוי',conflict:'התנגשויות',invalid:'דורשים תיקון',cancelled:'מבוטלים',missing:'חסרים בקובץ'};
const fieldLabels={catalog:'פריט קטלוג',project_system:'מערכת',quantity:'כמות',quantity_installed:'הותקן',status:'מצב',location:'מיקום',notes:'הערות',tag:'מזהה',title:'שם עבודה',description:'תיאור',due_date:'תאריך יעד',estimated_hours:'שעות מתוכננות'};
export function TableImportWizard({project,api,onClose,onImported}) {
  const [file,setFile]=useState(null),[data,setData]=useState(null),[configs,setConfigs]=useState([]),[projectId,setProjectId]=useState(project.id),[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState(null),[choices,setChoices]=useState({}),[decisions,setDecisions]=useState({}),[stale,setStale]=useState(false),[result,setResult]=useState(null),[filter,setFilter]=useState('all'),[bulk,setBulk]=useState({scope:'all',name:'',manufacturer:'',model:''});
  const act=async fn=>{setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}};
  const inspect=()=>act(async()=>{const body=new FormData();body.set('file',file);const result=await api('/table-import/inspect',{method:'POST',body});setData(result);setConfigs(result.tables.map(t=>({index:t.index,enabled:t.enabled,headerRow:t.headerRow,mapping:t.mapping,kind:t.kind,systemId:t.systemId||'',systemName:t.systemName,due:''})));setProjectId(result.detection.suggested||project.id);setReview(null);setChoices({});setDecisions({});});
  const updateConfig=(index,patch)=>{setConfigs(current=>current.map(c=>c.index===index?{...c,...patch}:c));setStale(true);};
  const changeChoice=(key,patch)=>{setChoices(current=>({...current,[key]:{...current[key],...patch,edits:{...current[key]?.edits,...patch.edits}}}));setStale(true);};
  const compare=()=>act(async()=>{const result=await api('/table-import/plan',{method:'POST',body:JSON.stringify({previewId:data.previewId,projectId,configs,choices})});setReview(result);setStale(false);setDecisions({});});
  const commit=()=>act(async()=>{const result=await api('/table-import/commit',{method:'POST',body:JSON.stringify({previewId:data.previewId,planId:review.planId,confirm:true,decisions})});setResult(result);await onImported(result.projectId);});
  const applyBulk=()=>{const edits=Object.fromEntries(Object.entries(bulk).filter(([k,v])=>k!=='scope'&&v.trim()));if(!Object.keys(edits).length)return;setChoices(current=>{const next={...current};for(const row of review.plan.filter(r=>r.kind&&(bulk.scope==='all'||r.type===bulk.scope)))next[row.key]={...next[row.key],edits:{...next[row.key]?.edits,...edits}};return next;});setStale(true);};
  const unresolved=review?.plan.some(r=>r.status==='conflict'&&!decisions[r.key]);
  const [showGroups,setShowGroups]=useState(false);
  const count=status=>review?.plan.filter(r=>r.status===status).length||0;
  return <AppModal title="ייבוא טבלה לפרויקט" subtitle="זיהוי מקומי · השוואת שינויים · שמירה רק לאחר אישור" onClose={()=>{if(!busy){if(data)api('/table-import/discard',{method:'POST',body:JSON.stringify({previewId:data.previewId})}).catch(()=>{});onClose();}}} closeOnBackdrop={false} className="table-import-modal">
    {error&&<div className="table-import-error" role="alert">{error}</div>}
    {result?<section className="table-import-success"><h3>הייבוא הושלם והקובץ צורף לפרויקט</h3><p>{result.summary.created} חדשים · {result.summary.updated} עודכנו · {result.summary.unchanged} ללא שינוי · {result.summary.skipped} דולגו</p><button className="primary-button" onClick={onClose}>סיום</button></section>:<>
    {!data?<section className="table-import-upload"><h3>כל טבלה נבדקת לפי המבנה שלה</h3><p>Excel, ODS, CSV או PDF עם טקסט. שורות סיכום אינן רכיבים; נדרש מזהה קבוע למניעת כפילויות.</p><input aria-label="קובץ לייבוא" type="file" accept=".xlsx,.ods,.csv,.pdf" disabled={busy} onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="primary-button" disabled={!file||busy} onClick={inspect}>{busy?'מנתח את הקובץ…':'בדיקה והצעת מיפוי'}</button><small>עד 15MB ו־5,000 שורות. בשלב זה לא נשמרים נתונים בפרויקט.</small></section>:<>
      <section className={`table-import-project ${data.detection.suggested===projectId?'detected':''}`}><label>פרויקט יעד<select aria-label="פרויקט יעד לייבוא" value={projectId} disabled={busy} onChange={e=>{setProjectId(e.target.value);setReview(null);setChoices({});setDecisions({});}}>{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><strong>{data.detection.suggested===projectId?'זוהה שם הפרויקט בטבלה · ניתן לשנות ידנית':data.detection.matches.length>1?'נמצאו כמה התאמות. בחרו את הפרויקט המתאים':'פרויקט שנבחר ידנית'}</strong></section>
      {data.warnings.map(w=><p className="table-import-warning" key={w}>{w}</p>)}
      {!review?<section className="table-import-mapping">{data.tables.map(t=>{const c=configs.find(c=>c.index===t.index);return <details key={t.index} open={c.enabled}><summary>{t.name} · {t.rows.length} שורות</summary><label><input type="checkbox" checked={c.enabled} disabled={busy} onChange={e=>updateConfig(t.index,{enabled:e.target.checked})}/>כלול גיליון</label>{c.enabled&&<>
        <div className="table-import-grid"><label>שורת כותרת<input type="number" min="1" max={t.rows.length} value={c.headerRow+1} onChange={e=>updateConfig(t.index,{headerRow:Number(e.target.value)-1})}/></label><label>יעד התוכן<select value={c.kind} onChange={e=>updateConfig(t.index,{kind:e.target.value})}><option value="equipment">מערכות ורכיבים</option><option value="task">משימות ועבודה מתוכננת</option></select></label>
        {c.kind==='equipment'?<><label>מערכת יעד<select value={c.systemId} onChange={e=>{const system=data.systems.find(s=>String(s.id)===e.target.value);updateConfig(t.index,{systemId:e.target.value,systemName:system?.name||c.systemName});}}><option value="">זיהוי לפי קטגוריה / מערכת חדשה</option>{data.systems.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{!c.systemId&&<label>מערכת מוצעת כשאין קטגוריה בשורה<input value={c.systemName} maxLength={120} onChange={e=>updateConfig(t.index,{systemName:e.target.value})}/></label>}</>:<label>תאריך יעד כשאינו בקובץ<DateInput type="date" value={c.due} onChange={e=>updateConfig(t.index,{due:e.target.value})}/></label>}</div>
        <div className="table-import-grid">{Object.entries(data.fields).map(([key,label])=><label key={key}>{label}<select aria-label={`${t.name} ${label}`} value={c.mapping[key]??''} onChange={e=>updateConfig(t.index,{mapping:{...c.mapping,[key]:e.target.value===''?null:Number(e.target.value)}})}><option value="">לא בקובץ</option>{(t.rows[c.headerRow]||[]).map((cell,i)=><option value={i} key={i}>{i+1}: {cell||'ללא כותרת'}</option>)}</select></label>)}</div>
        <div className="table-import-scroll"><table><thead><tr>{(t.rows[c.headerRow]||[]).map((v,i)=><th key={i}>{v||i+1}</th>)}</tr></thead><tbody>{t.rows.slice(c.headerRow+1,c.headerRow+5).map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div></>}</details>;})}</section>:<>
      {review.duplicate&&<p className="table-import-warning">הקובץ כבר יובא לפרויקט. יוצגו רק הבדלים בתוכן או במיפוי; לא יישמר מצורף כפול.</p>}
      <div className="table-import-counts">{Object.entries(labels).map(([key,label])=><button key={key} onClick={()=>setFilter(filter===key?'all':key)} aria-pressed={filter===key}>{count(key)} {label}</button>)}</div>
      <label><input type="checkbox" checked={showGroups} onChange={e=>setShowGroups(e.target.checked)}/>סיכום רכיבים זהים לפי קומה</label>{showGroups&&<div className="equipment-floor-groups">{groupEquipment(review.plan,{preview:true}).map(group=><details key={group.key}><summary>{group.floor} · {group.system} · {group.name} — כמות {group.quantity}, הותקנו {group.installed}, יתרה {Math.max(0,group.quantity-group.installed)}</summary><p>{group.items.map(item=>item.id).join(', ')}</p></details>)}</div>}
      <section className="table-import-bulk"><strong>דיוק שם, יצרן ודגם בקבוצה</strong><div className="table-import-grid"><label>להחיל על<select aria-label="קבוצת עריכה" value={bulk.scope} onChange={e=>setBulk({...bulk,scope:e.target.value})}><option value="all">כל הרכיבים</option>{[...new Set(review.plan.filter(r=>r.type).map(r=>r.type))].map(type=><option key={type}>{type}</option>)}</select></label>{[['name','שם רכיב'],['manufacturer','יצרן'],['model','דגם']].map(([key,label])=><label key={key}>{label}<input value={bulk[key]} maxLength={160} onChange={e=>setBulk({...bulk,[key]:e.target.value})} placeholder="ריק = ללא שינוי"/></label>)}</div><button disabled={busy} onClick={applyBulk}>החל על הקבוצה בתצוגה</button></section>
      <section className="table-import-rows">{review.plan.filter(r=>filter==='all'||r.status===filter).map((row,i)=><article className={`table-import-row ${row.status}`} key={`${row.key}-${i}`}><header><strong dir="auto">{row.id}</strong><span>{labels[row.status]} · {row.sheet} {row.row?`שורה ${row.row}`:''}</span></header>{row.problem&&<p>{row.problem}</p>}{row.kind&&<>
        <small>יעד: {row.kind==='task'?'משימות ועבודה':row.systemName} · מיקום: {row.location}</small>
        <div className="table-import-grid">{[['name','שם רכיב / עבודה'],['manufacturer','יצרן'],['model','דגם']].map(([key,label])=><label key={key}>{label}<input aria-label={`${row.id} ${label}`} value={choices[row.key]?.edits?.[key]??row[key]??''} maxLength={160} disabled={busy||row.status==='invalid'} onChange={e=>changeChoice(row.key,{edits:{[key]:e.target.value}})}/></label>)}</div>
        {(!row.linked)&&<label>קישור לרשומה קיימת במקום יצירה<select aria-label={`${row.id} רשומה קיימת`} value={choices[row.key]?.existingId||''} onChange={e=>changeChoice(row.key,{existingId:e.target.value})}><option value="">לפי המזהה הקבוע</option>{(row.kind==='task'?review.existingTasks:review.existingEquipment).map(e=><option value={e.id} key={e.id}>{e.label}</option>)}</select></label>}
        {row.changes.length>0&&<details><summary>מה ישתנה ({row.changes.length})</summary>{row.changes.map(c=><p key={c.field}><b>{fieldLabels[c.field]||c.field}:</b> {String(c.before??'ריק')} ← {String(c.after??'ריק')}</p>)}</details>}
        {!['invalid','cancelled'].includes(row.status)&&<label>{row.status==='conflict'?'בחירה נדרשת: שינוי ידני במערכת':'פעולה'}<select aria-label={`${row.id} פעולה`} value={decisions[row.key]||''} onChange={e=>setDecisions({...decisions,[row.key]:e.target.value})}><option value="">{row.status==='conflict'?'בחרו כיצד לטפל':'לייבא לפי ההשוואה'}</option><option value="file">להחיל שינויי הקובץ</option>{row.existingId&&<option value="keep">לשמור את ערכי המערכת</option>}<option value="skip">לדלג על השורה</option></select></label>}
      </>}</article>)}</section></>}
      <footer className="table-import-actions"><p>הקובץ המקורי יצורף לפרויקט. יצירה ועדכון יבוצעו רק בלחיצה על אישור; שורות חסרות או מבוטלות לא יימחקו. אין דיווח שעות בפועל.</p>{review&&<button disabled={busy} onClick={()=>setReview(null)}>חזרה למיפוי</button>}<button disabled={busy} onClick={compare}>{busy?'מעבד…':review?'השווה מחדש':'הצגת השינויים לפני אישור'}</button>{review&&<button className="primary-button" disabled={busy||stale||unresolved} onClick={commit}>אישור וייבוא לפרויקט</button>}{stale&&review&&<strong>יש להשוות מחדש לאחר העריכה.</strong>}</footer>
    </>}
    </>}
  </AppModal>;
}
