import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowLeft, BarChart3, BellRing, Bot, Check, CheckCircle2, Clock3, FolderKanban, Gauge, Layers3, Plus, RefreshCw, Save, Settings2, ShieldAlert, SlidersHorizontal, Sparkles, Trash2, Users } from "lucide-react";
import { TaskEditor } from "./Workspaces";
import "./my-work-enhancements.css";

const dateOnly=(value)=>String(value||"").slice(0,10);
const dayText=(value)=>value?new Date(`${dateOnly(value)}T00:00:00`).toLocaleDateString("he-IL",{day:"numeric",month:"short"}):"ללא תאריך";
const stageLabels={waiting:"בהמתנה",mobilization:"בהנעה",infrastructure:"תשתיות",threading:"השחלות",threading_done:"בוצעו השחלות",installation_a:"התקנות א׳",installation_b:"התקנות ב׳",installation_c:"התקנות ג׳",activation_programming:"הפעלות ותכנות",finishes:"פינישים",post_delivery:"מוכן למסירה"};
const priorityLabels={low:"נמוכה",normal:"רגילה",high:"גבוהה",urgent:"דחופה"};
const relevanceLabels={assignee:"מבצע",owner:"אחראי",manager:"מנהל הפרויקט",related:"קשור אליי"};

export function MyWorkWorkspace({api,user,projects,professionals,setNotice,openProject}){
  const [data,setData]=useState({sections:{overdue:[],today:[],upcoming:[],waiting:[]},stats:{},messages:[]});
  const [loading,setLoading]=useState(true);const [section,setSection]=useState("overdue");const [projectId,setProjectId]=useState("");const [priority,setPriority]=useState("");
  const [views,setViews]=useState([]);const [editor,setEditor]=useState(null);const [undo,setUndo]=useState(null);
  const load=async()=>{try{setLoading(true);const [work,saved]=await Promise.all([api("/my-work"),api("/saved-views?workspace=my-work")]);setData(work);setViews(saved.views);}catch(error){setNotice(error.message)}finally{setLoading(false)}};
  useEffect(()=>{load();const live=()=>load();window.addEventListener("projects:live-change",live);return()=>window.removeEventListener("projects:live-change",live)},[]);
  const source=data.sections[section]||[];
  const tasks=useMemo(()=>source.filter(task=>(!projectId||String(task.project_id)===projectId)&&(!priority||task.priority===priority)),[source,projectId,priority]);
  const update=async(task,patch,message)=>{try{await api(`/operations/tasks/${task.id}`,{method:"PATCH",body:JSON.stringify(patch)});setUndo({task,patch:{status:task.status},message});setNotice(message);await load()}catch(error){setNotice(error.message)}};
  const saveView=async()=>{const name=prompt("שם לתצוגה השמורה");if(!name)return;try{await api("/saved-views",{method:"POST",body:JSON.stringify({workspace:"my-work",name,filters:{section,projectId,priority}})});setNotice("התצוגה נשמרה עבורך");load()}catch(error){setNotice(error.message)}};
  const applyView=(view)=>{const filters=view.filters||{};setSection(filters.section||"overdue");setProjectId(String(filters.projectId||""));setPriority(filters.priority||"")};
  const saveTask=async(value)=>{try{await api(`/operations/tasks/${editor.id}`,{method:"PATCH",body:JSON.stringify(value)});setEditor(null);setNotice("המשימה עודכנה");load()}catch(error){setNotice(error.message)}};
  const sections=[["overdue","באיחור",data.stats.overdue,ShieldAlert],["today","היום",data.stats.today,Clock3],["upcoming","בהמשך",(data.sections.upcoming||[]).length,ArrowLeft],["waiting","ממתינות לתלות",data.stats.waiting,Layers3]];
  const personalName=String(user?.displayName||user?.username||"").trim().split(/\s+/)[0]||"שלך";
  return <div className="productivity-page my-work-page">
    <section className="productivity-hero"><div><span><Sparkles size={16}/> מרכז העבודה של {personalName}</span><h2>מה דורש את תשומת הלב שלך עכשיו, {personalName}?</h2><p>זהו סדר היום האישי שלך: משימות, חסמים והודעות שרלוונטיים אליך — לפי דחיפות, בלי לחפש בכל פרויקט בנפרד.</p></div><button onClick={load} disabled={loading}><RefreshCw size={17} className={loading?"spin":""}/> רענון</button></section>
    <div className="work-focus-stats">{sections.map(([id,label,count,Icon])=><button key={id} className={section===id?"active":""} onClick={()=>setSection(id)}><Icon size={20}/><span>{label}</span><strong>{count||0}</strong></button>)}</div>
    <section className="productivity-toolbar panel"><div className="saved-view-strip"><button onClick={saveView}><Save size={16}/> שמירת תצוגה</button>{views.map(view=><button key={view.id} onClick={()=>applyView(view)}>{view.name}</button>)}</div><div><select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">כל הפרויקטים</option>{projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">כל העדיפויות</option>{Object.entries(priorityLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{(projectId||priority)&&<button onClick={()=>{setProjectId("");setPriority("")}}>ניקוי</button>}</div></section>
    <section className="my-work-list panel">{loading?<div className="productivity-empty"><RefreshCw className="spin"/>טוען את סביבת העבודה...</div>:tasks.length?tasks.map(task=><article key={task.id} className={`focus-task ${task.critical?"critical":""}`}><button className="task-complete" title="סימון כהושלמה" onClick={()=>update(task,{status:"done"},"המשימה הושלמה")}><Check size={18}/></button><div className="focus-task-main" onClick={()=>setEditor(task)}><span>{task.project_name||"ללא פרויקט"} <i className={`task-relevance ${task.relevance||"related"}`}>{relevanceLabels[task.relevance]||relevanceLabels.related}</i></span><strong>{task.title}</strong><small>{task.dependency_title?`ממתינה ל: ${task.dependency_title}`:`תאריך סיום: ${dayText(task.due_date)}`} · {priorityLabels[task.priority]||task.priority}</small></div><div className="focus-task-actions"><button onClick={()=>update(task,{dueDate:new Date(Date.now()+86400000).toISOString().slice(0,10)},"המשימה הועברה למחר")}><Clock3 size={15}/> מחר</button><button onClick={()=>{const project=projects.find(item=>item.id===task.project_id);if(project)openProject(project)}}><FolderKanban size={15}/> פרויקט</button></div></article>):<div className="productivity-empty"><CheckCircle2 size={34}/><strong>הכול מטופל בתצוגה הזו</strong><span>אפשר לעבור לתצוגה אחרת או להסיר מסננים.</span></div>}</section>
    {!!data.messages.length&&<section className="attention-messages panel"><header><BellRing size={18}/><strong>הודעות שמחכות לך</strong><span>{data.messages.length}</span></header>{data.messages.slice(0,4).map(message=><div key={message.id}><b>{message.subject}</b><span>{message.sender_name}</span></div>)}</section>}
    {undo&&<div className="productivity-undo"><span>{undo.message}</span><button onClick={async()=>{await api(`/operations/tasks/${undo.task.id}`,{method:"PATCH",body:JSON.stringify(undo.patch)});setUndo(null);load()}}>ביטול פעולה</button><button onClick={()=>setUndo(null)}>×</button></div>}
    {editor&&<TaskEditor projects={projects} professionals={professionals} initial={editor} onClose={()=>setEditor(null)} onSave={saveTask}/>} 
  </div>
}

export function PortfolioControlWorkspace({api,setNotice,openProject,projects}){
  const [tab,setTab]=useState("health");const [health,setHealth]=useState([]);const [resources,setResources]=useState([]);const [loading,setLoading]=useState(true);
  const load=async()=>{try{setLoading(true);const [a,b]=await Promise.all([api("/portfolio-health"),api("/resource-workload")]);setHealth(a.projects);setResources(b.resources)}catch(error){setNotice(error.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const counts=useMemo(()=>({good:health.filter(x=>x.health.tone==="good").length,warning:health.filter(x=>x.health.tone==="warning").length,risk:health.filter(x=>x.health.tone==="risk").length}),[health]);
  return <div className="productivity-page"><section className="productivity-hero"><div><span><Gauge size={16}/> בקרת ביצוע</span><h2>תמונה ניהולית שאפשר לפעול ממנה</h2><p>בריאות פרויקטים ועומסי צוות מחושבים מנתוני אמת ומתורגמים לפעולה הבאה.</p></div><button onClick={load}><RefreshCw size={17}/> רענון</button></section><nav className="productivity-tabs"><button className={tab==="health"?"active":""} onClick={()=>setTab("health")}><Gauge size={17}/> בריאות פרויקטים</button><button className={tab==="resources"?"active":""} onClick={()=>setTab("resources")}><Users size={17}/> עומסי צוות</button></nav>
    {loading?<div className="productivity-empty panel"><RefreshCw className="spin"/>מחשב תמונת מצב...</div>:tab==="health"?<><div className="health-summary"><article className="good"><strong>{counts.good}</strong><span>תקינים</span></article><article className="warning"><strong>{counts.warning}</strong><span>דורשים תשומת לב</span></article><article className="risk"><strong>{counts.risk}</strong><span>בסיכון</span></article></div><section className="portfolio-health-grid">{health.map(item=><article key={item.id} className={`panel health-project ${item.health.tone}`} onClick={()=>{const project=projects.find(p=>p.id===item.id);if(project)openProject(project)}}><header><div><span>{stageLabels[item.stage]||item.stage}</span><h3>{item.name}</h3><small>{item.manager||"ללא מנהל"}</small></div><strong>{item.health.score}</strong></header><div className="health-meter"><i style={{width:`${item.health.score}%`}}/></div><ul>{item.health.reasons.length?item.health.reasons.map(reason=><li key={reason}>{reason}</li>):<li>ללא חריגות מהותיות</li>}</ul><footer>{item.health.nextAction}<ArrowLeft size={16}/></footer></article>)}</section></>:<section className="resource-board panel"><header><span>עומס ל־14 הימים הקרובים</span><strong>קיבולת מול שעות מתוכננות</strong></header>{resources.map(item=><article key={item.id}><div className="resource-person"><i style={{background:item.color||"#6d5ce7"}}>{item.display_name?.slice(0,2)}</i><span><b>{item.display_name}</b><small>{item.task_count} משימות · {item.overdue_count} באיחור</small></span></div><div className="resource-load"><span><b>{Number(item.allocated_hours)} שעות</b> מתוך {item.capacity_hours}</span><div><i className={item.utilization>100?"over":""} style={{width:`${Math.min(100,item.utilization)}%`}}/></div></div><strong className={item.utilization>100?"over":""}>{item.utilization}%</strong></article>)}</section>}
  </div>
}

export function ProductivitySettings({api,user,setNotice}){
  const [tab,setTab]=useState("templates");const [templates,setTemplates]=useState([]);const [rules,setRules]=useState([]);const [runs,setRuns]=useState([]);const [selected,setSelected]=useState(null);
  const load=async()=>{try{const [a,b]=await Promise.all([api("/project-templates"),api("/automation-rules")]);setTemplates(a.templates);setRules(b.rules);setRuns(b.runs)}catch(error){setNotice(error.message)}};useEffect(()=>{load()},[]);
  const addTemplate=async()=>{const name=prompt("שם התבנית");if(!name)return;try{await api("/project-templates",{method:"POST",body:JSON.stringify({name})});setNotice("התבנית נוצרה");load()}catch(error){setNotice(error.message)}};
  const addTemplateTask=async(template)=>{const title=prompt("כותרת המשימה בתבנית");if(!title)return;try{await api(`/project-templates/${template.id}/tasks`,{method:"POST",body:JSON.stringify({title,position:(template.tasks?.length||0)+1,durationDays:1})});load()}catch(error){setNotice(error.message)}};
  const addRule=async()=>{const name=prompt("שם האוטומציה");if(!name)return;const triggerType=prompt("אירוע: project_created / project_stage_changed / task_created / task_status_changed / task_overdue","task_overdue");if(!triggerType)return;const title=prompt("כותרת המשימה שתיווצר (אפשר להשאיר ריק כדי לשלוח הודעה למנהל)","");const actions=title?[{type:"create_task",title,dueDays:1,priority:"high"}]:[{type:"notify_manager",subject:"עדכון אוטומטי",body:name}];try{await api("/automation-rules",{method:"POST",body:JSON.stringify({name,triggerType,conditions:{},actions})});setNotice("האוטומציה פעילה");load()}catch(error){setNotice(error.message)}};
  return <section className="productivity-settings"><nav className="productivity-tabs"><button className={tab==="templates"?"active":""} onClick={()=>setTab("templates")}><Layers3 size={17}/> תבניות פרויקט</button><button className={tab==="automations"?"active":""} onClick={()=>setTab("automations")}><Bot size={17}/> אוטומציות</button></nav>{tab==="templates"?<><header className="settings-section-head"><div><h3>תבניות עבודה</h3><p>פתיחת פרויקט עם משימות, יעדי שעות ומבנה אחיד — בלי להתחיל מדף ריק.</p></div><button onClick={addTemplate}><Plus size={16}/> תבנית חדשה</button></header><div className="template-grid">{templates.map(template=><article className="panel" key={template.id}><header><span>{template.classification}</span><h4>{template.name}</h4><p>{template.description||"תבנית מותאמת של הארגון"}</p></header><div><b>{template.task_count||0}</b> משימות · <b>{template.installation_hours_target}</b> שעות התקנה</div><button onClick={()=>setSelected(selected===template.id?null:template.id)}>{selected===template.id?"הסתרת משימות":"צפייה במשימות"}</button>{selected===template.id&&<ul>{template.tasks.map(task=><li key={task.id}><span>{task.position}. {task.title}</span><button title="מחיקה" onClick={async()=>{await api(`/project-templates/${template.id}/tasks/${task.id}`,{method:"DELETE"});load()}}><Trash2 size={14}/></button></li>)}<li><button onClick={()=>addTemplateTask(template)}><Plus size={14}/> הוספת משימה</button></li></ul>}</article>)}</div></>:<><header className="settings-section-head"><div><h3>אוטומציות תפעוליות</h3><p>כללים שקופים ומתועדים. כל הפעלה נשמרת ביומן הרצות.</p></div><button onClick={addRule}><Plus size={16}/> אוטומציה חדשה</button></header><div className="automation-list panel">{rules.map(rule=><article key={rule.id}><i className={rule.active?"on":""}/><div><strong>{rule.name}</strong><span>{rule.trigger_type} · {rule.actions?.length||0} פעולות</span></div><button onClick={async()=>{await api(`/automation-rules/${rule.id}`,{method:"PATCH",body:JSON.stringify({active:!rule.active})});load()}}>{rule.active?"פעילה":"כבויה"}</button>{user.role==="admin"&&<button onClick={async()=>{if(confirm("למחוק את האוטומציה?")){await api(`/automation-rules/${rule.id}`,{method:"DELETE"});load()}}}><Trash2 size={15}/></button>}</article>)}{!rules.length&&<div className="productivity-empty">לא הוגדרו אוטומציות</div>}</div><div className="automation-runs panel"><h4>הרצות אחרונות</h4>{runs.slice(0,8).map(run=><div key={run.id}><span>{run.rule_name||"כלל שנמחק"}</span><b className={run.outcome}>{run.outcome==="completed"?"הושלם":"נכשל"}</b><small>{new Date(run.created_at).toLocaleString("he-IL")}</small></div>)}</div></>}</section>
}

export function ProjectGovernancePanel({project,api,user,setNotice}){
  const [baselines,setBaselines]=useState([]);const [changes,setChanges]=useState([]);const [form,setForm]=useState({title:"",description:"",priceImpact:"",scheduleImpactDays:""});
  const load=async()=>{try{const [a,b]=await Promise.all([api(`/projects/${project.id}/baselines`),api(`/projects/${project.id}/change-requests`)]);setBaselines(a.baselines);setChanges(b.changes)}catch(error){setNotice(error.message)}};useEffect(()=>{load()},[project.id]);
  const createBaseline=async()=>{try{await api(`/projects/${project.id}/baselines`,{method:"POST",body:JSON.stringify({label:`תכנית בסיס ${new Date().toLocaleDateString("he-IL")}`})});setNotice("תכנית הבסיס נשמרה");load()}catch(error){setNotice(error.message)}};
  const createChange=async(event)=>{event.preventDefault();try{await api(`/projects/${project.id}/change-requests`,{method:"POST",body:JSON.stringify({...form,status:"pending"})});setForm({title:"",description:"",priceImpact:"",scheduleImpactDays:""});setNotice("בקשת השינוי נפתחה");load()}catch(error){setNotice(error.message)}};
  const decide=async(change,status)=>{try{await api(`/projects/${project.id}/change-requests/${change.id}`,{method:"PATCH",body:JSON.stringify({status})});setNotice(status==="approved"?"השינוי אושר":"השינוי נדחה");load()}catch(error){setNotice(error.message)}};
  return <div className="governance-grid"><section className="panel baseline-card"><header><div><span><BarChart3 size={17}/> תכנית בסיס</span><h3>השוואת תכנון מול ביצוע</h3></div>{["admin","manager"].includes(user.role)&&<button onClick={createBaseline}><Save size={16}/> שמירת מצב נוכחי</button>}</header>{baselines.length?<div className="baseline-list">{baselines.map(item=><div key={item.id}><strong>{item.label}</strong><span>{new Date(item.created_at).toLocaleString("he-IL")}</span><small>{item.snapshot?.tasks?.length||0} משימות בנקודת הייחוס</small></div>)}</div>:<div className="productivity-empty">עדיין לא נשמרה תכנית בסיס. מומלץ לשמור לאחר אישור הלו״ז.</div>}</section><section className="panel change-card"><header><span><SlidersHorizontal size={17}/> בקרת שינויים</span><h3>השפעה על זמן ותקציב לפני ביצוע</h3></header><form onSubmit={createChange}><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="כותרת השינוי"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="מה השתנה ולמה?"/><div><label>השפעה כספית<input type="number" value={form.priceImpact} onChange={e=>setForm({...form,priceImpact:e.target.value})}/></label><label>השפעה בימים<input type="number" value={form.scheduleImpactDays} onChange={e=>setForm({...form,scheduleImpactDays:e.target.value})}/></label></div><button><Plus size={16}/> פתיחת בקשת שינוי</button></form><div className="change-list">{changes.map(change=><article key={change.id}><div><strong>{change.title}</strong><span>{change.status} · ₪{Number(change.price_impact).toLocaleString("he-IL")} · {change.schedule_impact_days} ימים</span></div>{change.status==="pending"&&["admin","manager"].includes(user.role)&&<aside><button onClick={()=>decide(change,"approved")}><Check size={15}/> אישור</button><button onClick={()=>decide(change,"rejected")}>דחייה</button></aside>}</article>)}</div></section></div>
}
