import { useMemo, useState } from "react";
import { ArrowDownAZ, ArrowUpAZ, ChevronDown, ChevronLeft, Copy, Download, GripVertical, Palette, Plus, RotateCcw, Trash2 } from "lucide-react";
import { MobileActionMenu } from "./MobileActionMenu";
import "./project-systems-board.css";

const BASE_FIELDS = [
  { key:"name", label:"רכיב", type:"text" },
  { key:"category", label:"קטגוריה", type:"status" },
  { key:"sku", label:"מק״ט", type:"text" },
  { key:"location", label:"מיקום", type:"text" },
  { key:"tag", label:"תיוג", type:"text" },
  { key:"quantity", label:"כמות", type:"number" },
  { key:"installed", label:"הותקן", type:"number" },
  { key:"status", label:"סטטוס", type:"status" },
];
const statusOptions=[['waiting','ממתין'],['in_progress','בביצוע'],['installed','הותקן']];

export function ProjectSystemsBoard({items,columns,fieldSettings=[],canEdit,canManage,user,api,apiRoot,projectId,onAdd,onReload,onDelete,setNotice}) {
  const [expanded,setExpanded]=useState(()=>new Set());
  const [expandedRows,setExpandedRows]=useState(()=>new Set());
  const [newColumn,setNewColumn]=useState('');
  const [newColumnType,setNewColumnType]=useState('text');
  const [draggedRow,setDraggedRow]=useState(null);
  const [draggedGroup,setDraggedGroup]=useState(null);
  const [groupSorts,setGroupSorts]=useState({});
  const [colorOverrides,setColorOverrides]=useState({});
  const [rowColorOverrides,setRowColorOverrides]=useState({});
  const settings=useMemo(()=>new Map(fieldSettings.map(item=>[item.field_key,item])),[fieldSettings]);
  const fields=useMemo(()=>[...BASE_FIELDS,...columns.map(column=>({key:column.column_key,label:column.label,type:column.column_type||'text',id:column.id,custom:true}))].map((field,index)=>({...field,label:settings.get(field.key)?.label||field.label,sort:Number(settings.get(field.key)?.sort_order??index)})).sort((a,b)=>a.sort-b.sort),[columns,settings]);
  const groups=useMemo(()=>{const map=new Map();for(const item of items){const key=String(item.system_id||'other');if(!map.has(key))map.set(key,{id:item.system_id,name:item.system_name||'ללא מערכת',type:item.system_type_name||'אחר',color:colorOverrides[key]||item.system_color||item.color||'#6957df',sort:Number(item.system_sort_order||0),items:[]});map.get(key).items.push(item)}return [...map.values()].sort((a,b)=>a.sort-b.sort)},[items,colorOverrides]);
  const save=async(item,body,notice='השורה עודכנה')=>{const hasColor=Object.prototype.hasOwnProperty.call(body,'rowColor'),key=String(item.id);if(hasColor)setRowColorOverrides(current=>({...current,[key]:body.rowColor}));try{await api(`/projects/${projectId}/equipment/${item.id}`,{method:'PATCH',body:JSON.stringify(body)});setNotice(notice);await onReload()}catch(error){if(hasColor)setRowColorOverrides(current=>{const next={...current};delete next[key];return next});setNotice(error.message)}};
  const saveGroup=async(group,body)=>{const hasColor=Object.prototype.hasOwnProperty.call(body,'color'),key=String(group.id);if(hasColor){setColorOverrides(current=>({...current,[key]:body.color}));setRowColorOverrides(current=>{const next={...current};for(const item of group.items)delete next[String(item.id)];return next})}try{await api(`/projects/${projectId}/system-board/${group.id}`,{method:'PATCH',body:JSON.stringify({title:body.title??group.name,color:body.color??group.color,sortOrder:group.sort,propagateColor:hasColor})});setNotice(hasColor?'צבע המערכת הוחל על כל הרכיבים':'המערכת עודכנה');await onReload()}catch(error){if(hasColor)setColorOverrides(current=>{const next={...current};delete next[key];return next});setNotice(error.message)}};
  const toggle=(setter,key)=>setter(current=>{const next=new Set(current);next.has(key)?next.delete(key):next.add(key);return next});
  const cycleSort=(groupId,fieldKey)=>setGroupSorts(current=>{const active=current[groupId],direction=active?.field===fieldKey?(active.direction==='asc'?'desc':active.direction==='desc'?'manual':'asc'):'asc';return {...current,[groupId]:{field:fieldKey,direction}}});
  const sortValue=(item,field)=>{if(field.key==='name')return item.name||'';if(field.key==='category')return item.system_name||'';if(field.key==='sku')return item.priority_sku||item.code||'';if(field.key==='quantity')return Number(item.quantity_ordered??item.quantity??0);if(field.key==='installed')return Number(item.quantity_installed||0);if(field.key==='status')return item.status||'';if(field.custom)return item.custom_values?.[field.key]??'';return item[field.key]??''};
  const addColumn=async()=>{if(!newColumn.trim())return;await api(`/projects/${projectId}/system-columns`,{method:'POST',body:JSON.stringify({label:newColumn.trim(),columnType:newColumnType})});setNewColumn('');await onReload()};
  const persistFields=async(next)=>{await api(`/projects/${projectId}/system-fields`,{method:'PATCH',body:JSON.stringify({fields:next.map(field=>({key:field.key,label:field.label}))})});await onReload()};
  const moveField=async(from,to)=>{if(from===to)return;const next=[...fields],[field]=next.splice(from,1);next.splice(to,0,field);await persistFields(next)};
  const renameField=async(field)=>{if(!canManage)return;const label=prompt('שם העמודה',field.label)?.trim();if(!label||label===field.label)return;if(field.custom)await api(`/projects/${projectId}/system-columns/${field.id}`,{method:'PATCH',body:JSON.stringify({label,columnType:field.type})});await persistFields(fields.map(item=>item.key===field.key?{...item,label}:item))};
  const duplicate=async(item)=>{const count=Number(prompt('כמה עותקים ליצור?','1'));if(!Number.isInteger(count)||count<1)return;if(count>50)return setNotice('אפשר לשכפל עד 50 עותקים בפעולה');await api(`/projects/${projectId}/equipment/${item.id}/duplicate`,{method:'POST',body:JSON.stringify({count})});setNotice(`${count} עותקים נוצרו`);await onReload()};
  const moveGroup=async(targetId)=>{if(draggedRow){await save(draggedRow,{projectSystemId:targetId},'הרכיב הועבר למערכת');setDraggedRow(null);return}if(!draggedGroup||String(draggedGroup)===String(targetId))return;const next=[...groups],from=next.findIndex(item=>String(item.id)===String(draggedGroup)),to=next.findIndex(item=>String(item.id)===String(targetId));const [group]=next.splice(from,1);next.splice(to,0,group);await api(`/projects/${projectId}/system-board-order`,{method:'PATCH',body:JSON.stringify({systemIds:next.map(item=>item.id)})});setDraggedGroup(null);await onReload()};
  const renderField=(field,item,group)=>{const common={disabled:!canEdit};if(field.key==='name')return <span className="subitem-name"><i draggable={canEdit} onDragStart={()=>setDraggedRow(item)}><GripVertical size={14}/></i><button type="button" onClick={()=>toggle(setExpandedRows,item.id)}><strong>{item.name}</strong><small>{expandedRows.has(item.id)?'צמצום':'הרחבת פרטים'}</small></button></span>;if(field.key==='category')return <label className="subitem-field"><small>{field.label}</small><select {...common} value={item.system_id||''} onChange={event=>save(item,{projectSystemId:Number(event.target.value)},'הרכיב הועבר למערכת')}>{groups.filter(entry=>entry.id).map(entry=><option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label>;if(field.key==='sku')return <label className="subitem-field"><small>{field.label}</small><input {...common} defaultValue={item.priority_sku||item.code||''} onBlur={event=>save(item,{sku:event.target.value})}/></label>;if(field.key==='location'||field.key==='tag')return <label className="subitem-field"><small>{field.label}</small><input {...common} defaultValue={item[field.key]||''} placeholder={`הוספת ${field.label}`} onBlur={event=>save(item,{[field.key]:event.target.value})}/></label>;if(field.key==='quantity')return <label className="subitem-field numeric"><small>{field.label}</small><input {...common} type="number" min="0" step="1" defaultValue={Number(item.quantity_ordered??item.quantity??0)} onBlur={event=>save(item,{quantity:Number(event.target.value)})}/></label>;if(field.key==='installed')return <label className="subitem-field numeric"><small>{field.label}</small><input {...common} type="number" min="0" step="1" defaultValue={Number(item.quantity_installed||0)} onBlur={event=>save(item,{quantityInstalled:Number(event.target.value)})}/></label>;if(field.key==='status')return <label className="subitem-field status-field"><small>{field.label}</small><select {...common} className={`monday-status ${item.status||'waiting'}`} value={item.status==='planned'?'waiting':item.status||'waiting'} onChange={event=>save(item,{status:event.target.value})}>{statusOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>;const value=item.custom_values?.[field.key]??'';return <label className="subitem-field"><small>{field.label}</small>{field.type==='status'?<select {...common} value={value} onChange={event=>save(item,{customValues:{...(item.custom_values||{}),[field.key]:event.target.value}})}><option value="">ללא מצב</option><option>ממתין</option><option>בביצוע</option><option>הושלם</option></select>:<input {...common} type={field.type==='number'?'number':'text'} defaultValue={value} onBlur={event=>save(item,{customValues:{...(item.custom_values||{}),[field.key]:field.type==='number'?Number(event.target.value):event.target.value}})}/>}</label>};
  const grid=`${fields.map(field=>field.key==='name'?'minmax(260px,2.4fr)':field.key==='sku'?'minmax(105px,.9fr)':field.type==='number'?'68px':'minmax(92px,.8fr)').join(' ')} 104px`;
  return <section className="project-systems-board modern-project-systems-board panel">
    <header className="project-systems-board-title"><div className="systems-board-heading"><span><h3>מערכות ורכיבים</h3><small>ניהול ציוד, מיקומים והתקדמות התקנה</small></span></div><div className="systems-board-actions"><a className="excel-export-button" href={`${apiRoot}/projects/${encodeURIComponent(projectId)}/systems.xlsx`} download><Download size={16}/>ייצוא Excel</a>{canManage&&<div className="add-column-control"><input value={newColumn} onChange={event=>setNewColumn(event.target.value)} placeholder="שם עמודה"/><select value={newColumnType} onChange={event=>setNewColumnType(event.target.value)}><option value="text">טקסט</option><option value="number">מספר</option><option value="status">מצב</option></select><button onClick={addColumn}><Plus size={15}/>עמודה</button></div>}{canEdit&&<button className="primary-button" onClick={onAdd}><Plus size={16}/>רכיב</button>}</div></header>
    <div className="project-systems-table">{groups.map(group=>{const sort=groupSorts[group.id]||{field:'name',direction:'manual'},sortField=fields.find(field=>field.key===sort.field)||fields[0],direction=sort.direction==='asc'?1:-1,groupItems=sort.direction==='manual'?group.items:[...group.items].sort((a,b)=>{const left=sortValue(a,sortField),right=sortValue(b,sortField);return direction*(typeof left==='number'&&typeof right==='number'?left-right:String(left).localeCompare(String(right),'he',{numeric:true}))}),total=group.items.reduce((sum,item)=>sum+Number(item.quantity_ordered??item.quantity??0),0),installed=group.items.reduce((sum,item)=>sum+Number(item.quantity_installed||0),0),open=expanded.has(group.id);return <article key={group.id} className={`project-system-item ${open?'is-open':''}`} style={{'--system-color':group.color}} onDragOver={event=>event.preventDefault()} onDrop={()=>moveGroup(group.id)}>
      <div className="project-system-row compact-parent" onClick={event=>{if(!event.target.closest('input,select,label,button,i'))toggle(setExpanded,group.id)}}><button className="system-expand" onClick={()=>toggle(setExpanded,group.id)}>{open?<ChevronDown size={18}/>:<ChevronLeft size={18}/>}</button><span className="system-title-cell"><i draggable={canEdit} onDragStart={()=>setDraggedGroup(group.id)}><GripVertical size={16}/></i><span className="system-identity"><input disabled={!canManage} defaultValue={group.name} onBlur={event=>saveGroup(group,{title:event.target.value})}/><small>{group.items.length} רכיבים</small></span></span><span className="system-category"><i style={{background:group.color}}/>{group.type}</span><b>{total}</b><b className="installed">{installed}</b><b className="remaining">{Math.max(0,total-installed)}</b><span className="system-row-tools"><label className="color-control" title="צבע המערכת" style={{'--selected-color':group.color}}><Palette size={14}/><input disabled={!canManage} type="color" value={group.color} onChange={event=>saveGroup(group,{color:event.target.value})}/></label></span></div>
      {open&&<div className="project-subitems"><div className="project-subitem-head board-fields-head" style={{gridTemplateColumns:grid}}>{fields.map((field,index)=>{const active=sort.field===field.key&&sort.direction!=='manual';return <span key={field.key} draggable={canManage} onDragStart={event=>event.dataTransfer.setData('text/plain',String(index))} onDragOver={event=>event.preventDefault()} onDrop={event=>moveField(Number(event.dataTransfer.getData('text/plain')),index)} onDoubleClick={()=>renameField(field)}><GripVertical size={12}/><b>{field.label}</b><button type="button" className={`column-sort ${active?'active':''}`} title={`מיון לפי ${field.label}`} onClick={()=>cycleSort(group.id,field.key)}>{active&&sort.direction==='desc'?<ArrowUpAZ size={14}/>:<ArrowDownAZ size={14}/>}</button></span>})}<span>פעולות</span></div>{groupItems.map(item=>{const itemKey=String(item.id),hasRowOverride=Object.prototype.hasOwnProperty.call(rowColorOverrides,itemKey),rowColor=hasRowOverride?(rowColorOverrides[itemKey]||group.color):(colorOverrides[String(group.id)]||item.row_color||group.color);return <div key={item.id} className={`project-subitem-row ${expandedRows.has(item.id)?'is-expanded':''}`} style={{'--row-color':rowColor,gridTemplateColumns:grid}}>{fields.map(field=><span className="field-slot" key={field.key}>{renderField(field,item,group)}</span>)}<span className="project-subitem-actions"><label className="color-control compact" style={{'--selected-color':rowColor}}><Palette size={13}/><input disabled={!canEdit} type="color" value={rowColor} onChange={event=>save(item,{rowColor:event.target.value})}/></label><button onClick={()=>duplicate(item)}><Copy size={14}/></button>{user.role==='admin'&&<button onClick={()=>onDelete(item)}><Trash2 size={14}/></button>}</span><span className="mobile-subitem-menu"><MobileActionMenu>{canEdit&&<label style={{'--selected-color':rowColor}}><i className="menu-color-dot"/><span>שינוי צבע</span><input type="color" value={rowColor} onChange={event=>save(item,{rowColor:event.target.value})}/></label>}{(item.row_color||hasRowOverride)&&<button onClick={()=>save(item,{rowColor:''})}><RotateCcw size={16}/><span>צבע המערכת</span></button>}<button onClick={()=>duplicate(item)}><Copy size={16}/><span>שכפול</span></button>{user.role==='admin'&&<button className="danger" onClick={()=>onDelete(item)}><Trash2 size={16}/><span>מחיקה</span></button>}</MobileActionMenu></span></div>})}<button className="project-add-subitem" onClick={onAdd}><Plus size={15}/>הוספת רכיב</button></div>}
    </article>})}</div>
  </section>;
}
