import { useEffect, useMemo, useState } from 'react';
import { Activity, Check, CheckCircle2, Command, CreditCard, FileText, Flag, Home, Mail, MapPin, MessageSquare, Phone, Plus, Settings, Trash2, UserRound, Users, X } from 'lucide-react';
import { TasksWorkspace, FinanceWorkspace } from './Workspaces';

const money = new Intl.NumberFormat('he-IL', { style: 'currency', currency: 'ILS', maximumFractionDigits: 0 });
const dateText = value => value ? new Date(value).toLocaleDateString('he-IL') : 'ללא תאריך';

function Modal({title,onClose,children}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal work-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span>כרטיס פרויקט</span><h2>{title}</h2></div><button onClick={onClose}><X/></button></div>{children}</div></div>}

export function ProjectWorkspace({ project, updateProject, api, apiRoot, user, projects, professionals, stageOptions, setNotice, setPage }) {
  const [tab,setTab]=useState('overview'); const [workspace,setWorkspace]=useState({tasks:[],milestones:[],payments:[],team:[],equipment:[],forms:[],files:[],updates:[],activity:[]}); const [note,setNote]=useState(''); const [modal,setModal]=useState(''); const [reference,setReference]=useState({roles:[],equipment:[]});
  const canEdit=['admin','manager','technician'].includes(user.role); const canManage=['admin','manager'].includes(user.role);
  const load=async()=>{try{setWorkspace(await api(`/projects/${encodeURIComponent(project.id)}/workspace`));}catch(e){setNotice(e.message)}};
  useEffect(()=>{load()},[project.id]);
  useEffect(()=>{if(!modal)return;Promise.all([api('/professional-roles'),api('/equipment-catalog')]).then(([a,b])=>setReference({roles:a.roles,equipment:b.items})).catch(e=>setNotice(e.message));},[modal]);
  const due=Number(project.value)-Number(project.paid); const completed=workspace.tasks.filter(x=>x.status==='done').length;
  const addUpdate=async e=>{e.preventDefault();if(!note.trim())return;try{await api(`/projects/${project.id}/updates`,{method:'POST',body:JSON.stringify({body:note})});setNote('');setNotice('העדכון פורסם לצוות');load()}catch(err){setNotice(err.message)}};
  const addTeam=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api(`/projects/${project.id}/team`,{method:'POST',body:JSON.stringify({professionalId:f.get('professionalId'),roleTypeId:f.get('roleTypeId'),isPrimary:f.get('isPrimary')==='on',notes:f.get('notes')})});setModal('');setNotice('איש הצוות שויך לפרויקט');load()}catch(err){setNotice(err.message)}};
  const addEquipment=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api(`/projects/${project.id}/equipment`,{method:'POST',body:JSON.stringify({catalogItemId:f.get('catalogItemId'),quantity:f.get('quantity'),location:f.get('location'),status:f.get('status'),serialNumber:f.get('serialNumber'),notes:f.get('notes')})});setModal('');setNotice('הציוד נוסף לפרויקט');load()}catch(err){setNotice(err.message)}};
  const deleteTeam=async x=>{if(!confirm(`להסיר את ${x.display_name} מהפרויקט?`))return;try{await api(`/projects/${project.id}/team/${x.professional_id}/${x.role_type_id}`,{method:'DELETE'});load()}catch(e){setNotice(e.message)}};
  const deleteEquipment=async x=>{if(!confirm(`להסיר את ${x.name}?`))return;try{await api(`/projects/${project.id}/equipment/${x.id}`,{method:'DELETE'});load()}catch(e){setNotice(e.message)}};
  const tabs=[['overview','סקירה'],['tasks','משימות ואבני דרך'],['systems','מערכות וצוות'],['forms','טפסים וקבצים'],['finance','כספים'],['activity','פעילות']];
  return <div className="project-detail project-workspace"><div className="project-hero panel"><div className="project-identity"><div className="project-home-icon"><Home size={27}/></div><div><div className="project-title-line"><h2>{project.name}</h2>{project.flag&&<span className="hero-flag"><Flag size={14}/>{project.flag}</span>}</div><p><UserRound size={15}/>{project.client}<span>·</span><MapPin size={15}/>{project.address}</p></div></div><div className="project-hero-actions"><button className="secondary-button" disabled={!canEdit} onClick={()=>setTab('activity')}><MessageSquare size={16}/>הוספת עדכון</button></div><div className="hero-metrics"><div><span>שלב נוכחי</span><select disabled={!canEdit} value={project.stage} onChange={e=>updateProject(project.id,{stage:e.target.value})}>{(stageOptions.length?stageOptions.map(i=>[i.metadata?.key||i.name,i.name]):[['planning','תכנון'],['infrastructure','תשתיות'],['installation','התקנה'],['programming','תכנות'],['handover','לקראת מסירה'],['completed','הושלם']]).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div><span>התקדמות</span><strong>{project.progress}%</strong><input disabled={!canEdit} type="range" min="0" max="100" value={project.progress} onChange={e=>updateProject(project.id,{progress:Number(e.target.value)})} style={{'--range':`${project.progress}%`}}/></div><div><span>בריאות הפרויקט</span><strong className={project.health<70?'health-risk':'health-good'}>{project.health}/100</strong><small>{project.health<70?'דורש תשומת לב':'מתנהל כשורה'}</small></div><div><span>מנהל פרויקט</span><select className="project-manager-select" disabled={!canManage} value={project.managerId||''} onChange={e=>updateProject(project.id,{managerId:e.target.value||null})}><option value="">ללא מנהל</option>{professionals.filter(p=>p.active&&p.affiliation==='company'&&p.roles.some(r=>r.key==='project_manager')).map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select></div><div><span>משימות</span><strong>{completed}/{workspace.tasks.length}</strong><small>{workspace.tasks.filter(x=>x.status!=='done'&&new Date(x.due_date)<new Date()).length} באיחור</small></div></div></div>
    <div className="detail-tabs">{tabs.map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}{id==='tasks'&&<em>{workspace.tasks.length}</em>}</button>)}</div>
    {tab==='overview'&&<div className="detail-grid"><div className="detail-main"><div className="panel overview-card"><div className="panel-head"><div><h3>אבני הדרך הקרובות</h3><span>{workspace.milestones.length} אבני דרך בפרויקט</span></div><button onClick={()=>setTab('tasks')}>ניהול מלא</button></div><div className="milestone-timeline">{workspace.milestones.length?workspace.milestones.slice(0,6).map(m=><div className={m.status==='completed'?'done':m.status==='in_progress'?'current':'future'} key={m.id}><span>{m.status==='completed'?<Check size={14}/>:''}</span><div><strong>{m.title}</strong><small>{dateText(m.due_date)} · {m.owner_name||'ללא אחראי'}</small></div></div>):<div className="inline-empty">טרם הוגדרו אבני דרך. ניתן להוסיף בלשונית המשימות.</div>}</div></div><div className="panel systems-card"><div className="panel-head"><div><h3>מערכות וציוד</h3><span>ציוד שהוקצה בפועל לפרויקט</span></div><button onClick={()=>setTab('systems')}>ניהול מערכות</button></div><div className="system-tiles">{workspace.equipment.slice(0,6).map((x,i)=><div key={x.id}><span className={`system-icon s${i%4}`}><Command size={18}/></span><strong>{x.name}</strong><small>{x.location||x.status} · {x.quantity} {x.unit}</small><CheckCircle2 size={17}/></div>)}{!workspace.equipment.length&&<div className="inline-empty">אין עדיין ציוד משויך לפרויקט.</div>}</div></div></div><div className="detail-side"><div className="panel contact-card"><div className="panel-head"><div><h3>פרטי לקוח</h3></div></div><div className="contact-person"><div className="client-avatar">{project.client.slice(0,2)}</div><div><strong>{project.client}</strong><span>לקוח ראשי</span></div></div>{project.phone&&<a href={`tel:${project.phone}`}><Phone size={16}/>{project.phone}</a>}{project.email&&<a href={`mailto:${project.email}`}><Mail size={16}/>{project.email}</a>}<p><MapPin size={16}/>{project.address}</p><button onClick={()=>setPage('clients')}>פתיחת מאגר הלקוחות</button></div><div className="panel money-summary"><div className="panel-head"><div><h3>סיכום כספי</h3></div></div><div><span>שווי הפרויקט</span><strong>{money.format(project.value)}</strong></div><div><span>שולם עד כה</span><strong className="green-text">{money.format(project.paid)}</strong></div><div className="due-row"><span>יתרה לגבייה</span><strong>{money.format(due)}</strong></div><div className="money-progress"><i style={{width:`${project.value?project.paid/project.value*100:0}%`}}/></div><button onClick={()=>setTab('finance')}>לפירוט תשלומים</button></div><form className="panel quick-notes" onSubmit={addUpdate}><div className="panel-head"><div><h3>עדכון מהיר לצוות</h3></div></div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="מה קרה, מה הוחלט ומה הפעולה הבאה?"/><button disabled={!note.trim()}>פרסום עדכון</button></form></div></div>}
    {tab==='tasks'&&<TasksWorkspace api={api} user={user} projects={projects} professionals={professionals} setNotice={setNotice} projectId={project.id} onDataChanged={load}/>}
    {tab==='finance'&&<FinanceWorkspace api={api} user={user} projects={projects} setNotice={setNotice} projectId={project.id}/>}
    {tab==='systems'&&<div className="project-two-columns"><section className="panel project-resource"><div className="panel-head"><div><h3>צוות הפרויקט</h3><span>עובדי חברה ואנשי מקצוע חיצוניים</span></div>{canManage&&<button onClick={()=>setModal('team')}><Plus size={15}/>שיוך איש צוות</button>}</div>{workspace.team.length?workspace.team.map(x=><div className="resource-row" key={`${x.professional_id}-${x.role_type_id}`}><span className="resource-avatar" style={{background:x.color}}>{x.display_name.slice(0,2)}</span><div><strong>{x.display_name}</strong><small>{x.role_name} {x.is_primary&&'· אחראי ראשי'}</small></div>{x.phone&&<a href={`tel:${x.phone}`}>{x.phone}</a>}{user.role==='admin'&&<button onClick={()=>deleteTeam(x)}><Trash2 size={15}/></button>}</div>):<div className="inline-empty">טרם שויך צוות לפרויקט.</div>}</section><section className="panel project-resource"><div className="panel-head"><div><h3>מערכות, ציוד ורכיבים</h3><span>כמות, מיקום, סטטוס ומספר סידורי</span></div>{canEdit&&<button onClick={()=>setModal('equipment')}><Plus size={15}/>הוספת ציוד</button>}</div>{workspace.equipment.length?workspace.equipment.map(x=><div className="resource-row" key={x.id}><span className="resource-avatar equipment"><Command size={17}/></span><div><strong>{x.name}</strong><small>{x.manufacturer} {x.model} · {x.quantity} {x.unit} · {x.location||'ללא מיקום'}</small></div><span className="resource-status">{x.status}</span>{user.role==='admin'&&<button onClick={()=>deleteEquipment(x)}><Trash2 size={15}/></button>}</div>):<div className="inline-empty">טרם שויך ציוד לפרויקט.</div>}</section></div>}
    {tab==='forms'&&<div className="project-two-columns"><section className="panel project-resource"><div className="panel-head"><div><h3>טפסי הפרויקט</h3><span>טיוטות, טפסים שהושלמו ואישורים</span></div><button onClick={()=>setPage('forms')}><Plus size={15}/>טופס חדש</button></div>{workspace.forms.length?workspace.forms.map(x=><div className="resource-row" key={x.id}><span className="resource-avatar equipment"><FileText size={17}/></span><div><strong>{x.title}</strong><small>{x.template_name} · {dateText(x.updated_at)}</small></div><span className={`resource-status ${x.status}`}>{x.status}</span></div>):<div className="inline-empty">אין טפסים המשויכים לפרויקט. יצירה מתוך מאגר הטפסים תשייך אותם אוטומטית.</div>}</section><section className="panel project-resource"><div className="panel-head"><div><h3>קבצים ומסמכים</h3><span>תוכניות, הזמנות, סריקות ותיעוד</span></div><button onClick={()=>setPage('master')}><Plus size={15}/>העלאת מסמך</button></div>{workspace.files.length?workspace.files.map(x=><a className="resource-row" key={x.id} href={`${apiRoot}/documents/${x.id}/download`}><span className="resource-avatar equipment"><FileText size={17}/></span><div><strong>{x.title||x.original_name}</strong><small>{x.category} · {(Number(x.size_bytes)/1024/1024).toFixed(1)} MB</small></div></a>):<div className="inline-empty">אין מסמכים בפרויקט.</div>}</section></div>}
    {tab==='activity'&&<div className="project-two-columns activity-layout"><form className="panel project-update-form" onSubmit={addUpdate}><h3>פרסום עדכון</h3><p>העדכון נשמר בהיסטוריה ומופיע לכל מי שמורשה לצפות בפרויקט.</p><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="סיכום ביקור, החלטה, חריגה או הנחיה לביצוע"/><button className="ops-primary" disabled={!note.trim()}><MessageSquare size={16}/>פרסום לצוות</button></form><section className="panel project-timeline"><div className="panel-head"><div><h3>יומן פעילות</h3><span>עדכונים ופעולות מערכת</span></div></div>{[...workspace.updates.map(x=>({...x,kind:'update',when:x.created_at})),...workspace.activity.map(x=>({...x,kind:'audit',when:x.created_at}))].sort((a,b)=>new Date(b.when)-new Date(a.when)).slice(0,100).map((x,i)=><div className="timeline-row" key={`${x.kind}-${x.id}-${i}`}><span><Activity size={15}/></span><div><strong>{x.kind==='update'?x.body:`${x.user_name||'מערכת'} · ${x.action}`}</strong><small>{x.kind==='update'?(x.created_by_name||'משתמש'):x.entity_type} · {new Date(x.when).toLocaleString('he-IL')}</small></div></div>)}</section></div>}
    {modal==='team'&&<Modal title="שיוך איש צוות" onClose={()=>setModal('')}><form className="work-form" onSubmit={addTeam}><label>איש מקצוע<select name="professionalId" required><option value="">בחירה מהמאגר</option>{professionals.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.displayName} · {p.companyName||'עובד חברה'}</option>)}</select></label><label>תפקיד בפרויקט<select name="roleTypeId" required><option value="">בחירת תפקיד</option>{reference.roles.filter(r=>r.active).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="wide check-label"><input type="checkbox" name="isPrimary"/>אחראי ראשי בתפקיד זה</label><label className="wide">הערות<textarea name="notes"/></label><div className="wide form-actions"><button type="button" className="ops-secondary" onClick={()=>setModal('')}>ביטול</button><button className="ops-primary">שיוך לפרויקט</button></div></form></Modal>}
    {modal==='equipment'&&<Modal title="הוספת ציוד לפרויקט" onClose={()=>setModal('')}><form className="work-form" onSubmit={addEquipment}><label className="wide">פריט קטלוג<select name="catalogItemId" required><option value="">בחירה מהקטלוג</option>{reference.equipment.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name} {x.manufacturer} {x.model}</option>)}</select></label><label>כמות<input name="quantity" type="number" min="0" step="0.1" defaultValue="1"/></label><label>מיקום בפרויקט<input name="location" placeholder="למשל: ארון תקשורת קומה 1"/></label><label>סטטוס<select name="status"><option value="planned">מתוכנן</option><option value="ordered">הוזמן</option><option value="delivered">סופק</option><option value="installed">הותקן</option><option value="tested">נבדק</option></select></label><label>מספר סידורי<input name="serialNumber"/></label><label className="wide">הערות<textarea name="notes"/></label><div className="wide form-actions"><button type="button" className="ops-secondary" onClick={()=>setModal('')}>ביטול</button><button className="ops-primary">הוספה לפרויקט</button></div></form></Modal>}
  </div>;
}
